name: "Home Assistant Roon UI"
description: "Have a full Roon UI in Home Assistant."
version: "1.0"
slug: "home-assistant-roon-ui"
init: false
arch:
  - aarch64
  - amd64
host_network: true
options:
  verbose_logging: false
schema:
  verbose_logging: bool